class_path: minerva.models.ssl.diet.DIET
init_args:
  backbone:
    class_path: minerva.models.nets.time_series.imu_transformer._IMUTransformerEncoder
    init_args:
      input_shape: [6,60]
      transformer_dim : 64
      encode_position : True
      nhead: 8
      dim_feedforward : 128
      transformer_dropout : 0.1
      transformer_activation : "gelu"
      num_encoder_layers : 6
  linear_head: null
  num_data: null
  flatten: True
  adapter: null
  loss: null
  learning_rate: 3e-4
  weight_decay: 3e-4
  wca_scheduler_total_epochs: null