class_path: minerva.models.ssl.diet.DIET
init_args:
  backbone:
    class_path: minerva.models.nets.time_series.cnns.CNN_PF_Backbone
    init_args:
      include_middle: True
      flatten: True
  linear_head: null
  num_data: null
  flatten: True
  adapter: null
  loss: null
  learning_rate: 3e-4
  weight_decay: 3e-4
  wca_scheduler_total_epochs: null