class_path: minerva.models.ssl.diet.DIET
init_args:
  backbone:
    class_path: minerva.models.nets.tnc.RnnEncoder
    init_args:
      hidden_size: 100
      in_channel: 6
      encoding_size: 320
      cell_type: 'GRU'
      num_layers: 1
      dropout: 0
      bidirectional: True
      permute: True
  linear_head: null
  num_data: null
  flatten: True
  adapter: null
  loss: null
  learning_rate: 3e-4
  weight_decay: 3e-4
  wca_scheduler_total_epochs: null