class_path: minerva.models.ssl.diet.DIET
init_args:
  backbone:
    class_path: minerva.models.nets.lfr_har_architectures.HARSCnnEncoder
    init_args:
      dim: 2304
      input_channel: 6
      inner_conv_output_dim: 1280
  linear_head: null
  num_data: null
  flatten: True
  adapter: null
  loss: null
  learning_rate: 3e-4
  weight_decay: 3e-4
  wca_scheduler_total_epochs: null