class_path: minerva.models.ssl.tfc.TFC_Model
init_args:
  input_channels: 6
  batch_size: 64
  TS_length: 60
  num_classes: 6
  single_encoding_size: 128
  backbone:
    class_path: minerva.models.nets.tfc.TFC_Backbone
    init_args:
      input_channels: 6
      TS_length: 60
      single_encoding_size: 128
      time_encoder:
        class_path: minerva.models.nets.lfr_har_architectures.HARSCnnEncoder
        init_args:
          dim: 2304
          input_channel: 6
          inner_conv_output_dim: 1280
      frequency_encoder:
        class_path: minerva.models.nets.lfr_har_architectures.HARSCnnEncoder
        init_args:
          dim: 2304
          input_channel: 6
          inner_conv_output_dim: 1280
  pred_head: null
  