class_path: minerva.models.ssl.tfc.TFC_Model
init_args:
  input_channels: 6
  batch_size: 64
  TS_length: 60
  num_classes: 6
  single_encoding_size: 128
  backbone:
    class_path: minerva.models.nets.tfc.TFC_Backbone
    init_args:
      input_channels: 6
      TS_length: 60
      single_encoding_size: 128
      time_encoder:
        class_path: minerva.models.nets.time_series.resnet._ResNet1D
        init_args:
          input_shape: [6, 60]
          residual_block_cls: minerva.models.nets.time_series.resnet.ResNetSEBlock
      frequency_encoder:
        class_path: minerva.models.nets.time_series.resnet._ResNet1D
        init_args:
          input_shape: [6, 60]    
          residual_block_cls: minerva.models.nets.time_series.resnet.ResNetSEBlock
  pred_head: null
  