class_path: minerva.models.ssl.tfc.TFC_Model
init_args:
  input_channels: 6
  batch_size: 64
  TS_length: 60
  num_classes: 6
  single_encoding_size: 64
  backbone:
    class_path: minerva.models.nets.tfc.TFC_Backbone
    init_args:
      input_channels: 6
      TS_length: 60
      single_encoding_size: 64
      time_encoder:
        class_path: minerva.models.nets.tnc.TSEncoder
        init_args:
          input_dims: 6
          output_dims: 32
          hidden_dims: 32
          depth: 10
          permute: True
      frequency_encoder:
        class_path: minerva.models.nets.tnc.TSEncoder
        init_args:
          input_dims: 6
          output_dims: 32
          hidden_dims: 32
          depth: 10
          permute: True
  pred_head: null
  