class_path: minerva.models.ssl.tfc.TFC_Model
init_args:
  input_channels: 6
  batch_size: 64
  TS_length: 60
  num_classes: 6
  single_encoding_size: 128
  backbone:
    class_path: minerva.models.nets.tfc.TFC_Backbone
    init_args:
      input_channels: 6
      TS_length: 60
      single_encoding_size: 128
      time_encoder:
        class_path: minerva.models.nets.tnc.RnnEncoder
        init_args:
          hidden_size: 100
          in_channel: 6
          encoding_size: 320
          cell_type: 'GRU'
          num_layers: 1
          dropout: 0
          bidirectional: True
          permute: True
      frequency_encoder:
        class_path: minerva.models.nets.tnc.RnnEncoder
        init_args:
          hidden_size: 100
          in_channel: 6
          encoding_size: 320
          cell_type: 'GRU'
          num_layers: 1
          dropout: 0
          bidirectional: True
          permute: True
  pred_head: null
  